prefix               = "ro"
project              = "Remessa Online ECS Project"
contact              = "contact@juliosaraiva.com"
bastion_ssh_key_name = "ssh_bastion_server"
ecr_image_nginx      = "docker.io/nginx:latest"