name: Development

on:
  pull_request:
    branches:
      - dev

env:
  TERRAFORM_VERSION: 0.15.0
  AWS_DEFAULT_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_db_username: ${{ secrets.TF_VAR_db_username }}
  TF_VAR_db_password: ${{ secrets.TF_VAR_db_password }}
jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment:
      name: staging
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - uses: hashicorp/setup-terraform@v1
    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true
    - name: Terraform Init
      id: init
      run: terraform init
      continue-on-error: true
    - name: Select Staging Workspace
      run: terraform workspace select staging
      continue-on-error: true
    - id: check_workspace
      run: terraform workspace show
    - id: output_workspace
      run: echo ::set-output name=key::${{ steps.check_workspace.outputs['stdout'] }}
    - name: Create Staging workspace
      run: terraform workspace new staging
      if: ${{ steps.output_workspace.outputs.key != 'staging' }}
    - name: Terraform plan
      id: plan
      run: terraform plan -no-color
