name: Terraform

on:
  pull_request:
    branches:
      - dev

env:
  TERRAFORM_VERSION: 0.15.0
  AWS_DEFAULT_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment:
      name: staging
    strategy:
      matrix:
        dir:
          - .
          - modules/networking
          - modules/bastion
          - modules/ecs
          - modules/elb
          - modules/rds
    steps:
    - uses: actions/checkout@v2.1.0
    - uses: hashicorp/setup-terraform@v1
    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true
    - name: Terraform Init
      id: init
      run: terraform init
    - name: Select Staging Workspace
      run: terraform workspace select staging
      continue-on-error: true
    - id: check_workspace
      run: terraform workspace show
    - id: output_workspace
      run: echo ::set-output name=key::${{ steps.check_workspace.outputs['stdout'] }}
    - name: Create Staging workspace
      run: terraform workspace new staging
      if: ${{ steps.output_workspace.outputs.key != 'staging' }}
    - name: Terraform validate
      run: terraform validate ${{ matrix.dir }}
    - name: Terraform plan
      id: plan
      if: github.event_name == 'pull_request'
      run: terraform plan -no-color
      continue-on-error: true
