name: Terraform
on:
  pull_request:

env:
  TERRAFORM_VERSION: 0.15.0
  AWS_DEFAULT_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  workspace:
    name: Create Workspace
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment:
      name: staging
    steps:
    - uses: actions/checkout@v2.1.0
    - uses: hashicorp/setup-terraform@v1
    - name: Terraform Init
      id: init
      run: terraform init
    - name: Create Staging Workspace
      id: workspace
      run: terraform workspace new staging
    - name: Terraform validate
      id: validate
      run: terraform validate ${{ matrix.dir }}

  format:
    name: Format
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment:
      name: staging
    steps:
    - uses: actions/checkout@v2.1.0
    - uses: hashicorp/setup-terraform@v1
    - run: terraform workspace list
    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true


